### ISSUE TITLE
I dont know how to run the program

### ISSUE THREAD

**Issue by Tonyztj** [SSARCandy/panoramas-image-stitching#14]
请问怎么修改运行的图像文件，还有它会自动把结果保存到result里吗？

**Comment by SSARCandy** [comment]
please read the README.

```
$ python main.py <input img dir>

# for example
$ python ./main.py ../input_image/Xue-Mountain-Enterance/
```

Output
The program will output:

Every stitched images, with filename 0.jpg, 1.jpg, 2.jpg, ...
A aligned image aligned.jpg
A cropped image cropped.jpg
