### ISSUE TITLE
跑通示例图片，存在拼缝明显和无法消除视差的问题

### ISSUE THREAD

**Issue by RUIXUEZHAOFENGNIAN** [SSARCandy/panoramas-image-stitching#24]
用代码跑通示例图片，存在拼缝明显和无法消除视差的问题。请问作者是否会进一步优化

**Comment by SSARCandy** [comment]
please give me some example results

**Comment by RUIXUEZHAOFENGNIAN** [comment]
![cropped_indoor](https://user-images.githubusercontent.com/9213483/203526406-47b57458-699c-4321-a318-4444436fdb42.jpg)
![cropped_mountain](https://user-images.githubusercontent.com/9213483/203526415-0bdcad75-ebb9-45a1-b19a-8c86ae1280a4.jpg)

**Comment by SSARCandy** [comment]
in the 1st example, it actually is due to lighting issues (camera ISO or exposure time different)
in the 2nd example, due to a small calibration error of camera placement, it should be possible to improve by doing local area wrap, but I do not intend to do ATM.
