### ISSUE TITLE
A way to visualize keypoints on the panorama

### ISSUE THREAD

**Issue by Linardos** [SSARCandy/panoramas-image-stitching#8]
For the purposes of a project I'm working on I would like to be able to use your code to produce a panorama, but also be able to map the keypoints from the original features to the panorama. Is there a way to keep this information in the results? So that essentially one would be able to visualize the original keypoints on the panorama?

**Comment by SSARCandy** [comment]
please reference to https://github.com/SSARCandy/panoramas-image-stitching/blob/master/src/Stitch_two_image.ipynb

may help

**Comment by Linardos** [comment]
It really did help!
I ended up padding the original image with zeroes so that it matches the size of the panorama, then did feature matching between the padded image and the panorama, the result looks like this:

![matched](https://user-images.githubusercontent.com/26694607/54030300-13d96600-41a3-11e9-8e24-cb7f44e7bfa1.png)

I will soon try to apply this on more than 2 images. It is very likely that I will need to use SIFT instead of Harris corner though, would that radically change your implementation?

**Comment by SSARCandy** [comment]
Great, the figure looks good 👍 
And no, switch from Harris to SIFT I think just need changing the feature detection part only,
